name: First workflow
#this trigger means means we can manually trigger this workflow
on: workflow_dispatch 
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        # for each step we can define predefined Actions(maybe from marketplace) or use commands to run in shell
        run: |
          echo "Hello world first line"
          echo "Hello world second line"
      - name: Print goodbye
        run: echo "Done -bye"
