name: First workflow
on: workflow_dispatch
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world"
      - name: Print goodbye
        run: echo "Done -bye"
